---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
seeds <- read_csv("/home/john/basketball/march_madness/2019/data/DataFiles/NCAATourneySeeds.csv")
results <- read_csv("/home/john/basketball/march_madness/2019/data/DataFiles/NCAATourneyCompactResults.csv")
```

Join the two...

```{r}
colnames(results)
```

```{r}
colnames(seeds)
```


```{r}
results_w_seeds <- 
  inner_join(results %>% select(Season,WTeamID,LTeamID),
             seeds %>% mutate(WSeed = str_sub(Seed,2,3)),
             by = c('Season','WTeamID' = 'TeamID')) %>%
  inner_join(.,
             seeds %>% mutate(LSeed = str_sub(Seed,2,3)),
             by = c('Season','LTeamID' = 'TeamID')) %>%
  mutate(matchup = paste0(pmin(WSeed,LSeed),"-",pmax(WSeed,LSeed))) %>%
  select(Season,WSeed,LSeed,matchup)
```

```{r}
head(results_w_seeds)
```


```{r}
season_first_tourney_day <-
results %>%
  group_by(Season) %>%
  summarise(first_day = min(DayNum))
```

```{r}
results_tourney_day <-
  results %>%
  inner_join(season_first_tourney_day, by = 'Season') %>%
  mutate(days_since_first = DayNum - first_day)
```

```{r}
table(results_day_since_first$days_since_first)
```

Which years were there opening games?

```{r}
results_tourney_day %>%
  group_by(Season) %>%
  summarise(count = n_distinct(days_since_first))
```

```{r}
results_tourney_day <-
  results_tourney_day%>%
  mutate(round  = case_when(
    Season %in% c(1985:2000) & days_since_first %in% c(0,1)  ~ 1,
    Season %in% c(1985:2000) & days_since_first %in% c(2,3)  ~ 2,
    Season %in% c(1985:2000) & days_since_first %in% c(7,8)  ~ 3,
    Season %in% c(1985:2000) & days_since_first %in% c(9,10) ~ 4,
    Season %in% c(1985:2000) & days_since_first %in% c(16)   ~ 5,
    Season %in% c(1985:2000) & days_since_first %in% c(18)   ~ 6,
    Season %in% c(2001:2010) & days_since_first %in% c(0)    ~ 0,
    Season %in% c(2001:2010) & days_since_first %in% c(2,3)  ~ 1,
    Season %in% c(2001:2010) & days_since_first %in% c(4,5)  ~ 2,
    Season %in% c(2001:2010) & days_since_first %in% c(9,10) ~ 3,
    Season %in% c(2001:2010) & days_since_first %in% c(11,12)~ 4,
    Season %in% c(2001:2010) & days_since_first %in% c(18)   ~ 5,
    Season %in% c(2001:2010) & days_since_first %in% c(20)   ~ 6,
    Season %in% c(2011:2018) & days_since_first %in% c(0,1)  ~ 0,
    Season %in% c(2011:2018) & days_since_first %in% c(2,3)  ~ 1,
    Season %in% c(2011:2018) & days_since_first %in% c(4,5)  ~ 2,
    Season %in% c(2011:2018) & days_since_first %in% c(9,10) ~ 3,
    Season %in% c(2011:2018) & days_since_first %in% c(11,12)~ 4,
    Season %in% c(2011:2018) & days_since_first %in% c(18)   ~ 5,
    Season %in% c(2011:2018) & days_since_first %in% c(20)   ~ 6,
    TRUE ~ NA_real_))

```


```{r}
colnames(results_tourney_day)
```


```{r}
results_w_seeds <-
  results_tourney_day %>% select(Season,WTeamID,LTeamID,round) %>%
  inner_join(.,
             seeds %>% mutate(WSeed = str_sub(Seed,2,3)),
             by = c('Season','WTeamID' = 'TeamID')) %>%
  inner_join(.,
             seeds %>% mutate(LSeed = str_sub(Seed,2,3)),
             by = c('Season','LTeamID' = 'TeamID')) %>%
  select(Season,WSeed,LSeed,round)
```

```{r}
head(results_w_seeds)
```

# Most Common:

## Champion
```{r}
results_w_seeds %>%
  filter(round == 6) %>%
  group_by(WSeed) %>%
  summarise(count = n()) %>%
  ungroup() %>%
  mutate(pct = count/sum(count))
```

```{r}
results_w_seeds %>%
  filter(round == 6) %>%
  arrange(Season) %>%
  select(Season,WSeed)
```

## Championship Matchup
```{r}
results_w_seeds %>%
  filter(round == 6) %>%
  group_by(WSeed,LSeed) %>%
  summarise(count = n()) %>%
  ungroup() %>%
  mutate(pct = count/sum(count)) %>%
  arrange(desc(pct))
```
```{r}
results_w_seeds %>%
  filter(round == 5) %>%
  group_by(Season,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  mutate(championshipgame = paste0(`01`,`02`,`03`,`04`,`05`,`06`,`07`,`08`)) %>%
  group_by(championshipgame) %>%
  summarise(count = n()) %>%
  mutate(pct = count/sum(count)) %>%
  arrange(desc(count))
```

## Final Four Teams
```{r}
results_w_seeds %>%
  filter(round == 4) %>%
  group_by(Season,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  mutate(finalfour = paste0(`01`,`02`,`03`,`04`,`05`,`06`,`07`,`08`,`09`,`10`,`11`)) %>%
  group_by(finalfour) %>%
  summarise(count = n()) %>%
  mutate(pct = count/sum(count)) %>%
  arrange(desc(count))
```

```{r}
results_w_seeds %>%
  filter(round == 4) %>%
  group_by(Season,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  ungroup() %>%
  summarise_if(is.numeric,mean,na.rm=TRUE) 
```

## How often does:
## each number of seeds






### Most likely championship matchup, given a one won

## Elite 8

```{r}
results_w_seeds %>%
  filter(round == 3) %>%
  group_by(Season,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  mutate(sweet16 = paste0(`01`,`02`,`03`,`04`,`05`,`06`,`07`,`08`,`09`,`10`,`11`,`12`)) %>%
  group_by(sweet16) %>%
  summarise(count = n()) %>%
  mutate(pct = count/sum(count)) %>%
  arrange(desc(count))
```

```{r}
results_w_seeds %>%
  filter(round == 3) %>%
  group_by(Season,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  mutate(sweet16 = paste0(`01`,`02`,`03`,`04`,`05`,`06`,`07`,`08`,`09`,`10`,`11`,`12`)) %>%
  ungroup() %>%
  summarise_if(is.numeric,mean,na.rm=TRUE) 
```







## Sweet 16
```{r}
results_w_seeds %>%
  filter(round == 2) %>%
  group_by(Season,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  mutate(sweet16 = paste0(`01`,`02`,`03`,`04`,`05`,`06`,`07`,`08`,`09`,`10`,`11`,`12`,`13`,`14`,`15`)) %>%
  group_by(sweet16) %>%
  summarise(count = n()) %>%
  mutate(pct = count/sum(count)) %>%
  arrange(desc(count))
```


```{r}
results_w_seeds %>%
  filter(round == 2) %>%
  group_by(Season,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  ungroup() %>%
  summarise_if(is.numeric,mean,na.rm=TRUE) 
```



## Round of 32


```{r}
results_w_seeds %>%
  filter(round == 1) %>%
  group_by(Season,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  mutate(roundof32 = paste0(`01`,`02`,`03`,`04`,`05`,`06`,`07`,`08`,`09`,`10`,`11`,`12`,`13`,`14`,`15`,`16`)) %>%
  group_by(roundof32) %>%
  summarise(count = n()) %>%
  mutate(pct = count/sum(count)) %>%
  arrange(desc(count))
```

```{r}
results_w_seeds %>%
  filter(round == 1) %>%
  group_by(Season,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  ungroup() %>%
  summarise_if(is.numeric,mean,na.rm=TRUE) 
  
```

