---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(knitr)
seeds <- read_csv("/home/john/projects/basketball/march_madness/2020/data/MDataFiles_Stage1/MNCAATourneySeeds.csv")
results <- read_csv("/home/john/projects/basketball/march_madness/2020/data/MDataFiles_Stage1/MNCAATourneyCompactResults.csv")
```

```{r}
results_w_seeds <- 
  inner_join(results %>% select(Season,WTeamID,LTeamID),
             seeds %>% mutate(WSeed = str_sub(Seed,2,3)),
             by = c('Season','WTeamID' = 'TeamID')) %>%
  inner_join(.,
             seeds %>% mutate(LSeed = str_sub(Seed,2,3)),
             by = c('Season','LTeamID' = 'TeamID')) %>%
  mutate(matchup = paste0(pmin(WSeed,LSeed),"-",pmax(WSeed,LSeed))) %>%
  select(Season,WSeed,LSeed,matchup)
```

```{r}
season_first_tourney_day <-
results %>%
  group_by(Season) %>%
  summarise(first_day = min(DayNum))
```

```{r}
results_tourney_day <-
  results %>%
  inner_join(season_first_tourney_day, by = 'Season') %>%
  mutate(days_since_first = DayNum - first_day)
```

```{r}
table(results_tourney_day$days_since_first)
```

```{r}
results_tourney_day %>%
  group_by(Season) %>%
  summarise(count = n_distinct(days_since_first))
```



```{r}
results_tourney_day <-
  results_tourney_day%>%
  mutate(round  = case_when(
    Season %in% c(1985:2000) & days_since_first %in% c(0,1)  ~ 1,
    Season %in% c(1985:2000) & days_since_first %in% c(2,3)  ~ 2,
    Season %in% c(1985:2000) & days_since_first %in% c(7,8)  ~ 3,
    Season %in% c(1985:2000) & days_since_first %in% c(9,10) ~ 4,
    Season %in% c(1985:2000) & days_since_first %in% c(16)   ~ 5,
    Season %in% c(1985:2000) & days_since_first %in% c(18)   ~ 6,
    Season %in% c(2001:2010) & days_since_first %in% c(0)    ~ 0,
    Season %in% c(2001:2010) & days_since_first %in% c(2,3)  ~ 1,
    Season %in% c(2001:2010) & days_since_first %in% c(4,5)  ~ 2,
    Season %in% c(2001:2010) & days_since_first %in% c(9,10) ~ 3,
    Season %in% c(2001:2010) & days_since_first %in% c(11,12)~ 4,
    Season %in% c(2001:2010) & days_since_first %in% c(18)   ~ 5,
    Season %in% c(2001:2010) & days_since_first %in% c(20)   ~ 6,
    Season %in% c(2011:2019) & days_since_first %in% c(0,1)  ~ 0,
    Season %in% c(2011:2019) & days_since_first %in% c(2,3)  ~ 1,
    Season %in% c(2011:2019) & days_since_first %in% c(4,5)  ~ 2,
    Season %in% c(2011:2019) & days_since_first %in% c(9,10) ~ 3,
    Season %in% c(2011:2019) & days_since_first %in% c(11,12)~ 4,
    Season %in% c(2011:2019) & days_since_first %in% c(18)   ~ 5,
    Season %in% c(2011:2019) & days_since_first %in% c(20)   ~ 6,
    TRUE ~ NA_real_))

```


```{r}
results_w_seeds <-
  results_tourney_day %>% select(Season,WTeamID,LTeamID,round) %>%
  inner_join(.,
             seeds %>% mutate(WSeed = str_sub(Seed,2,3)),
             by = c('Season','WTeamID' = 'TeamID')) %>%
  inner_join(.,
             seeds %>% mutate(LSeed = str_sub(Seed,2,3)),
             by = c('Season','LTeamID' = 'TeamID')) %>%
  select(Season,WSeed,LSeed,round)
```


```{r}
head(results_w_seeds)
```

```{r}
results_w_seeds %>%
  filter(round > 0) %>%
  group_by(Season,round,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  ungroup() %>%
  select(-Season) %>%
  group_by(round) %>%
  summarise_if(is_numeric,mean,na.rm = TRUE) %>%
  mutate_if(is_numeric,round,1) %>%
  arrange(desc(round)) %>%
  mutate(round = case_when(round == 1 ~ "Round of 32",
                           round == 2 ~ "Sweet 16",
                           round == 3 ~ "Elite Eight",
                           round == 4 ~ "Final Four",
                           round == 5 ~ "Championship Game",
                           round == 6 ~ "Champion")) %>%
  kable()
```

Last 5 Years (2015-2019)
```{r}
last5years <- 
results_w_seeds %>%
  filter(round > 0, Season %in% c(2015:2019)) %>%
    group_by(Season,round,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  ungroup() %>%
  select(-Season) %>%
  group_by(round) %>%
  summarise_if(is_numeric,mean,na.rm = TRUE) %>%
  mutate_if(is_numeric,round,1) %>%
  arrange(desc(round)) %>%
  mutate(round = case_when(round == 1 ~ "Round of 32",
                           round == 2 ~ "Sweet 16",
                           round == 3 ~ "Elite Eight",
                           round == 4 ~ "Final Four",
                           round == 5 ~ "Championship Game",
                           round == 6 ~ "Champion"),
         when = "last5")
```



Five Years Before That (2010-2014)
```{r}
nextlast5years <-
 results_w_seeds %>%
  filter(round > 0, Season %in% c(2010:2014)) %>% 
  group_by(Season,round,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  ungroup() %>%
  select(-Season) %>%
  group_by(round) %>%
  summarise_if(is_numeric,mean,na.rm = TRUE) %>%
  mutate_if(is_numeric,round,1) %>%
  arrange(desc(round)) %>%
  mutate(round = case_when(round == 1 ~ "Round of 32",
                           round == 2 ~ "Sweet 16",
                           round == 3 ~ "Elite Eight",
                           round == 4 ~ "Final Four",
                           round == 5 ~ "Championship Game",
                           round == 6 ~ "Champion"),
         when = "5beforethat")
```


```{r}
compare5 <-
last5years %>%
  bind_rows(.,
            nextlast5years) %>%
  arrange(round)
```


## Same thing for 10 years
```{r}
last10years <- 
results_w_seeds %>%
  filter(round > 0, Season %in% c(2010:2019)) %>%
    group_by(Season,round,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  ungroup() %>%
  select(-Season) %>%
  group_by(round) %>%
  summarise_if(is_numeric,mean,na.rm = TRUE) %>%
  mutate_if(is_numeric,round,1) %>%
  arrange(desc(round)) %>%
  mutate(round = case_when(round == 1 ~ "Round of 32",
                           round == 2 ~ "Sweet 16",
                           round == 3 ~ "Elite Eight",
                           round == 4 ~ "Final Four",
                           round == 5 ~ "Championship Game",
                           round == 6 ~ "Champion"),
         when = "last10")
```


```{r}
nextlast10years <-
  results_w_seeds %>%
  filter(round > 0, Season %in% c(2000:2009)) %>%
  group_by(Season,round,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  ungroup() %>%
  select(-Season) %>%
  group_by(round) %>%
  summarise_if(is_numeric,mean,na.rm = TRUE) %>%
  mutate_if(is_numeric,round,1) %>%
  arrange(desc(round)) %>%
  mutate(round = case_when(round == 1 ~ "Round of 32",
                           round == 2 ~ "Sweet 16",
                           round == 3 ~ "Elite Eight",
                           round == 4 ~ "Final Four",
                           round == 5 ~ "Championship Game",
                           round == 6 ~ "Champion"),
         when = "last10beforethat")
```

```{r}
compare10 <-
last10years %>%
  bind_rows(.,
            nextlast10years) %>%
  arrange(round)
```


## What's in Massey Scores?

```{r}
massey <- read_csv("/home/john/projects/basketball/march_madness/2020/data/MDataFiles_Stage1/MMasseyOrdinals.csv")
```

```{r}
head(massey)
```


```{r}
massey %>%
  group_by(SystemName) %>%
  tally
```

Focus on AP rankings    

```{r}
ap_rankings <-
  massey %>%
  filter(SystemName == 'AP')
```

```{r}
summary(ap_rankings$OrdinalRank)
```

```{r}
top1_churn <-
  ap_rankings %>%
  filter(OrdinalRank == 1) %>%
  group_by(Season) %>%
  summarise(churn1 = n_distinct(TeamID))
```


```{r}
top5_churn <-
  ap_rankings %>%
  filter(OrdinalRank <= 5) %>%
  group_by(Season) %>%
  summarise(churn5 = n_distinct(TeamID))
```

```{r}
top10_churn <-
  ap_rankings %>%
  filter(OrdinalRank <= 10) %>%
  group_by(Season) %>%
  summarise(churn10 = n_distinct(TeamID))
```

```{r}
top25_churn <-
  ap_rankings %>%
  filter(OrdinalRank <= 25) %>%
  group_by(Season) %>%
  summarise(churn25 = n_distinct(TeamID))
```



```{r}
churn_data <-
  top1_churn %>%
  inner_join(top5_churn,  by = "Season") %>%
  inner_join(top10_churn, by = "Season") %>%
  inner_join(top25_churn, by = "Season")
```

```{r}
head(churn_data)
```

```{r}
cor(churn_data[,c(2,3,4,5)])
```

```{r}
install.packages("GGally")
library(GGally)
ggpairs(churn_data[,c(2,3,4,5)])
```

```{r}
churn_data_matrix <- churn_data[,c(2,3,4)]
colMeans(churn_data_matrix)
churn_data_matrix_scaled <- scale(churn_data_matrix,center=TRUE,scale=TRUE)
churn_data_matrix_scaled
```




```{r}
ggplot(data = churn_data,
       aes(x = Season, y = churn1)) +
  geom_point()

ggplot(data = churn_data,
       aes(x = Season, y = churn5)) +
  geom_point()

ggplot(data = churn_data,
       aes(x = Season, y = churn10)) +
  geom_point()

ggplot(data = churn_data,
       aes(x = Season, y = churn25)) +
  geom_point()
```



Run k-means
```{r}
?kmeans
k2 <- kmeans(churn_data_matrix_scaled,2)
k3 <- kmeans(churn_data_matrix_scaled,3)
k4 <- kmeans(churn_data_matrix_scaled,4)
```

```{r}
churn_data$k2 <- k2$cluster
churn_data$k3 <- k3$cluster
churn_data$k4 <- k4$cluster
```



## Look at averages in these different groups in the tournament

```{r}
vals <-
churn_data %>%
  group_by(k2) %>%
  summarise(values = paste(Season,collapse = ","))
```

```{r}
?str_split
as.numeric(str_split(vals$values[1], pattern = ",", simplify = TRUE))
```


```{r}
k2_vals <- 
  churn_data %>%
  group_by(k2) %>%
  summarise(values = paste(Season,collapse = ","))

results_a <- 
  results_w_seeds %>%
  filter(round > 0, Season %in% as.numeric(str_split(k2_vals$values[1], pattern = ",", simplify = TRUE))) %>%
  group_by(Season,round,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  ungroup() %>%
  select(-Season) %>%
  group_by(round) %>%
  summarise_if(is_numeric,mean,na.rm = TRUE) %>%
  mutate_if(is_numeric,round,1) %>%
  arrange(desc(round)) %>%
  mutate(round = case_when(round == 1 ~ "Round of 32",
                           round == 2 ~ "Sweet 16",
                           round == 3 ~ "Elite Eight",
                           round == 4 ~ "Final Four",
                           round == 5 ~ "Championship Game",
                           round == 6 ~ "Champion"),
        cluster = "a",
        num_seasons = length(as.numeric(str_split(k2_vals$values[1], pattern = ",", simplify = TRUE))))

results_b <- 
  results_w_seeds %>%
  filter(round > 0, Season %in% as.numeric(str_split(k2_vals$values[2], pattern = ",", simplify = TRUE))) %>%
  group_by(Season,round,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  ungroup() %>%
  select(-Season) %>%
  group_by(round) %>%
  summarise_if(is_numeric,mean,na.rm = TRUE) %>%
  mutate_if(is_numeric,round,1) %>%
  arrange(desc(round)) %>%
  mutate(round = case_when(round == 1 ~ "Round of 32",
                           round == 2 ~ "Sweet 16",
                           round == 3 ~ "Elite Eight",
                           round == 4 ~ "Final Four",
                           round == 5 ~ "Championship Game",
                           round == 6 ~ "Champion"),
         cluster = "b",
         num_seasons = length(as.numeric(str_split(k2_vals$values[2], pattern = ",", simplify = TRUE))))


compare2 <-
results_a %>%
  bind_rows(.,
            results_b) %>%
  arrange(round) %>%
     select(round,cluster,num_seasons,setdiff(colnames(results_a),c('round','cluster','season')))
compare2
```


```{r}
k3_vals <- 
  churn_data %>%
  group_by(k3) %>%
  summarise(values = paste(Season,collapse = ","))

results_a <- 
  results_w_seeds %>%
  filter(round > 0, Season %in% as.numeric(str_split(k3_vals$values[1], pattern = ",", simplify = TRUE))) %>%
  group_by(Season,round,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  ungroup() %>%
  select(-Season) %>%
  group_by(round) %>%
  summarise_if(is_numeric,mean,na.rm = TRUE) %>%
  mutate_if(is_numeric,round,1) %>%
  arrange(desc(round)) %>%
  mutate(round = case_when(round == 1 ~ "Round of 32",
                           round == 2 ~ "Sweet 16",
                           round == 3 ~ "Elite Eight",
                           round == 4 ~ "Final Four",
                           round == 5 ~ "Championship Game",
                           round == 6 ~ "Champion"),
        cluster = "a",
        num_seasons = length(as.numeric(str_split(k3_vals$values[1], pattern = ",", simplify = TRUE))))

results_b <- 
  results_w_seeds %>%
  filter(round > 0, Season %in% as.numeric(str_split(k3_vals$values[2], pattern = ",", simplify = TRUE))) %>%
  group_by(Season,round,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  ungroup() %>%
  select(-Season) %>%
  group_by(round) %>%
  summarise_if(is_numeric,mean,na.rm = TRUE) %>%
  mutate_if(is_numeric,round,1) %>%
  arrange(desc(round)) %>%
  mutate(round = case_when(round == 1 ~ "Round of 32",
                           round == 2 ~ "Sweet 16",
                           round == 3 ~ "Elite Eight",
                           round == 4 ~ "Final Four",
                           round == 5 ~ "Championship Game",
                           round == 6 ~ "Champion"),
         cluster = "b",
         num_seasons = length(as.numeric(str_split(k3_vals$values[2], pattern = ",", simplify = TRUE))))

results_c <- 
  results_w_seeds %>%
  filter(round > 0, Season %in% as.numeric(str_split(k3_vals$values[3], pattern = ",", simplify = TRUE))) %>%
  group_by(Season,round,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  ungroup() %>%
  select(-Season) %>%
  group_by(round) %>%
  summarise_if(is_numeric,mean,na.rm = TRUE) %>%
  mutate_if(is_numeric,round,1) %>%
  arrange(desc(round)) %>%
  mutate(round = case_when(round == 1 ~ "Round of 32",
                           round == 2 ~ "Sweet 16",
                           round == 3 ~ "Elite Eight",
                           round == 4 ~ "Final Four",
                           round == 5 ~ "Championship Game",
                           round == 6 ~ "Champion"),
         cluster = "c",
         num_seasons = length(as.numeric(str_split(k3_vals$values[3], pattern = ",", simplify = TRUE))))

compare3 <-
results_a %>%
  bind_rows(.,
            results_b) %>%
  bind_rows(.,
            results_c) %>%
  arrange(round) %>%
    select(round,cluster,num_seasons,setdiff(colnames(results_a),c('round','cluster','season')))
compare3
```

```{r}
k4_vals <- 
  churn_data %>%
  group_by(k3) %>%
  summarise(values = paste(Season,collapse = ","))

results_a <- 
  results_w_seeds %>%
  filter(round > 0, Season %in% as.numeric(str_split(k4_vals$values[1], pattern = ",", simplify = TRUE))) %>%
  group_by(Season,round,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  ungroup() %>%
  select(-Season) %>%
  group_by(round) %>%
  summarise_if(is_numeric,mean,na.rm = TRUE) %>%
  mutate_if(is_numeric,round,1) %>%
  arrange(desc(round)) %>%
  mutate(round = case_when(round == 1 ~ "Round of 32",
                           round == 2 ~ "Sweet 16",
                           round == 3 ~ "Elite Eight",
                           round == 4 ~ "Final Four",
                           round == 5 ~ "Championship Game",
                           round == 6 ~ "Champion"),
        cluster = "a",
        num_seasons = length(as.numeric(str_split(k4_vals$values[1], pattern = ",", simplify = TRUE))))

results_b <- 
  results_w_seeds %>%
  filter(round > 0, Season %in% as.numeric(str_split(k4_vals$values[2], pattern = ",", simplify = TRUE))) %>%
  group_by(Season,round,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  ungroup() %>%
  select(-Season) %>%
  group_by(round) %>%
  summarise_if(is_numeric,mean,na.rm = TRUE) %>%
  mutate_if(is_numeric,round,1) %>%
  arrange(desc(round)) %>%
  mutate(round = case_when(round == 1 ~ "Round of 32",
                           round == 2 ~ "Sweet 16",
                           round == 3 ~ "Elite Eight",
                           round == 4 ~ "Final Four",
                           round == 5 ~ "Championship Game",
                           round == 6 ~ "Champion"),
         cluster = "b",
         num_seasons = length(as.numeric(str_split(k4_vals$values[2], pattern = ",", simplify = TRUE))))

results_c <- 
  results_w_seeds %>%
  filter(round > 0, Season %in% as.numeric(str_split(k4_vals$values[3], pattern = ",", simplify = TRUE))) %>%
  group_by(Season,round,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  ungroup() %>%
  select(-Season) %>%
  group_by(round) %>%
  summarise_if(is_numeric,mean,na.rm = TRUE) %>%
  mutate_if(is_numeric,round,1) %>%
  arrange(desc(round)) %>%
  mutate(round = case_when(round == 1 ~ "Round of 32",
                           round == 2 ~ "Sweet 16",
                           round == 3 ~ "Elite Eight",
                           round == 4 ~ "Final Four",
                           round == 5 ~ "Championship Game",
                           round == 6 ~ "Champion"),
         cluster = "c",
         num_seasons = length(as.numeric(str_split(k4_vals$values[3], pattern = ",", simplify = TRUE))))

results_d <- 
  results_w_seeds %>%
  filter(round > 0, Season %in% as.numeric(str_split(k4_vals$values[3], pattern = ",", simplify = TRUE))) %>%
  group_by(Season,round,WSeed) %>%
  summarise(count = n()) %>%
  spread(key = WSeed, value = count, fill = 0) %>%
  ungroup() %>%
  select(-Season) %>%
  group_by(round) %>%
  summarise_if(is_numeric,mean,na.rm = TRUE) %>%
  mutate_if(is_numeric,round,1) %>%
  arrange(desc(round)) %>%
  mutate(round = case_when(round == 1 ~ "Round of 32",
                           round == 2 ~ "Sweet 16",
                           round == 3 ~ "Elite Eight",
                           round == 4 ~ "Final Four",
                           round == 5 ~ "Championship Game",
                           round == 6 ~ "Champion"),
         cluster = "d",
         num_seasons = length(as.numeric(str_split(k4_vals$values[4], pattern = ",", simplify = TRUE))))

compare4 <-
results_a %>%
  bind_rows(.,
            results_b) %>%
  bind_rows(.,
            results_c) %>%
  bind_rows(.,
            results_d) %>%
  arrange(round) %>%
  select(round,cluster,num_seasons,setdiff(colnames(results_a),c('round','cluster','season')))
compare4
```


```{r}
k2
```

```{r}
k3
```

